### PR TITLE
Share frameworks for carthage

### PR DESCRIPTION
**Pull request by dungi**

### CODE REVIEW

**Comment by zolomatok** [comment]
I greatly value your contribution!

**Comment by zolomatok** [comment]
@dunqi For some reason I get "Dependency "Johnny" has no shared framework schemes" when I try to build with Carthage. If I look at the project under Carthage/Checkout, the schemes are not shared. But if I clone the repo myself to another folder, the schemes are marked as shared.

Do you know why this would happen?

**Comment by zolomatok** [comment]
your branch works, but my master doesn't

**Comment by dungi** [comment]
Do you released a new version? Try to checkout with the latest "hash"

**Comment by dungi** [comment]
Carthage update with no information just check out the latest version (tag 2.0.0)

**Comment by zolomatok** [comment]
@dunqi Oh thanks for the help, I didn't know that, I'll push a new tag!

**Pull request merged**
